#!/usr/bin/env bash

set -e
set -x

if [ "$SOURCE_ROOT" == "" ]; then
    SOURCE_ROOT="$(readlink -f $(dirname $0))/../"
fi

if [ "$BUILD_ROOT" == "" ]; then
    BUILD_ROOT="$SOURCE_ROOT/build/"
fi

if [ "$VALIDATE_ROOT" == "" ]; then
    VALIDATE_ROOT="$BUILD_ROOT/validate"
fi

main() {
    EXTRA_CMAKE_ARGS="$@"

    mkdir -p "$VALIDATE_ROOT"
    cd "$VALIDATE_ROOT"

    run_fresh_cmake "$SOURCE_ROOT"

    validate_compiler "GNU" gcc g++
    validate_compiler "clang" clang clang++
}

# runs in subshell
validate_compiler() (
    local name="$1"
    export CC="$2"
    export CXX="$3"

    mkdir -p "$VALIDATE_ROOT"

    cd "$VALIDATE_ROOT"

    echo "Running validation with compiler family: $name"

    for build_type in Debug Release; do
        for full_build in ON OFF; do
            run_validation -DVERBOSE=ON -DFULL_BUILD="$full_build" -DCMAKE_BUILD_TYPE="$build_type"
        done
    done
)

run_fresh_cmake() {
    rm -f CMakeCache.txt
    cmake $EXTRA_CMAKE_ARGS "$@"
}

run_validation() {
    run_fresh_cmake "$@" "$SOURCE_ROOT"

    # I couldn't find another way to keep cmake from deleting
    # the boost directory during make clean
    if [ -e jackalope-boost-prefix ]; then
        hide jackalope-boost-prefix

        make clean

        unhide jackalope-boost-prefix
    fi

    for target in all test; do
        cmake --build . --target "$target"
    done

    # first packaging makes a tarball
    package
    package DEB
}

package() {
    local generator_name="$1"

    if [ "$generator_name" != "" ]; then
        cmake -DCPACK_GENERATOR="$generator_name" "$SOURCE_ROOT"
    fi

    cmake --build . --target package
}

hide() {
    local hide_path=".hide.$1"

    if [ -e "$hide_path" ]; then
        rm -f "$hide_path"
    fi

    mv "$1" "$hide_path"
}

unhide() {
    mv ".hide.$1" "$1"
}

main "$@"
